spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
server:
  port: 12333
  servlet:
    context-path: /geduca