spring:
  profiles:
    include: common
  datasource:
    url: jdbc:postgresql://localhost:5432/geduca
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
#    url: jdbc:mysql://localhost:3306/db_geduca?createDatabaseIfNotExist=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8&characterSetResults=UTF-8&useTimezone=true&serverTimezone=UTC
#    username: root
#    password: null
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
        default_schema: db_geduca
        show_sql: true
        use_sql_comments: true
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
            
geduca:
  urls-liberadas: >
    /teste/**   
  urls-principais-liberadas: >
    /teste/**
  origin-pemitida: http://localhost:4200
  enable-https: false